### ISSUE TITLE
Find all grant token string and introduce them in SDK

### ISSUE THREAD

**Issue by rkharisov** [hyperledger/iroha-java#123]
Currently grant tokens are specified as regular structs. Need to find them in Iroha2 source code and copy them in the SDK.

Current permission list https://github.com/hyperledger/iroha-java/blob/iroha2-dev/modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/permissions.kt
Grant tests included in https://github.com/hyperledger/iroha/blob/iroha2/core/src/smartcontracts/isi/permissions.rs

**Comment by appetrosyan** [comment]
https://github.com/hyperledger/iroha/pull/2156

May be relevant
