### ISSUE TITLE
Query filtering 

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha-java#234]
hyperledger/iroha#2270 added the functionality. The functionality must be properly implemented in the Iroha Java and Kotlin SDKs.

**Comment by appetrosyan** [comment]
Relevant information 

With Iroha now supports query filtering. This implies a radical change to the Query infrastructure (reflected in the schema). While Pagination is url-encoded, the QueryRequest's payload field (of type Payload) now has an extra field populated with a PredicateBox instance. 

PredicateBox alongside predicate::string::Predicate, predicate::value::Predicate and a few other types in the data_model/src/predicate.rs are used to build up Filters. Simple logic, nesting and basic targeting of containers is supported. More will be explained once SDKs have managed to reproduce the old behaviour. 

To reproduce the old behaviour you need to construct the Payload with the predicate::value::Predicate::Pass variant, which ignores input and returns true. 

The filter only applies to queries which return Value::Vec. This is because Predicates targeting Metadata are not useful. 

The total returned will be changed shortly in a separate PR.

GitHub (https://github.com/hyperledger/iroha/pull/2270)
[feature] #1998: Add filters to queries by appetrosyan · Pull Request #2270 · hyperledger/iroha
Signed-off-by: Aleksandr Petrosyan a-p-petrosyan@yandex.ru

**Comment by Mingela** [comment]
Relevant to repair metadata filtering + tests (once it's done on Iroha side)
