### ISSUE TITLE
Block streaming endless processing interface

### ISSUE THREAD

**Issue by Mingela** [hyperledger/iroha-java#330]
Previous issue: https://github.com/hyperledger/iroha-java/issues/320
Implementation of which introduced just a way to query N blocks starting from a specific height due to requirement ambiguity.

In this issue it's suggested to implement an 'endless loop wrapper', like `Flux`, `Observable` or `Flow` as indicated in previous discussion in both #320 and #328

**Comment by appetrosyan** [comment]
Ideally, the block streaming API should be _asynchronous_ and _concurrent_, where the blocks are automatically parsed from the endpoint and streamed into middleware such as the one used in the Laos implementation.

**Comment by Mingela** [comment]
I'd say concurrency is a debatable requirement since parsing logic might be dependent on a state expected by a change introduced in a previous block. We might consider some optional complications in the interface to be able to define such kind of dependencies to enforce sequential block processing within just the dependency specified though I'd like to hear more about this from Laos use case perspective.
Alternatively, we could just iteratively expand the interface and begin with just _async_ relaxing _concurrent_ property.
