### ISSUE TITLE
Git branching model

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha-java#408]
Do in `iroha-java` as was done in [#4433](https://github.com/hyperledger/iroha/issues/4433)

**Comment by Mingela** [comment]
Considering there have been multiple Iroha tracks (DEV/STABLE/LTS) SDK referencing is a bit different from the link.
We're used to work as follows:
1) sdk's `iroha2-dev` references iroha's `iroha2-stable`
2) sdk's `iroha2-main` references iroha's `iroha2-lts`

It's hardly makes sense to build anything for `iroha2-dev` so for projects using Iroha there might be a need to have lts-SDK and the latest stable-SDK which both should be supported. Let's decide about the tags only policy later, for now just swap iroha1 with iroha2 content in terms of 'defaults'

**Comment by nxsaken** [comment]
Nothing needs to be done for now then.

**Comment by mversic** [comment]
@mingela since you've made the `iroha2-dev` a default branch of your repository, it's the same as if you have `main` branch. Effectively your `iroha2-dev` branch **is `main` branch** from the perspective of git, it's just renamed. You are breaking convention a little bit here calling, what should be `main` branch, `iroha2-dev`.

If you rename `iroha2-lts` into `main` that will be confusing because you will have a `main` branch that is not default. Just try cloning the repository and see which branch git puts you in.

The way I see this is that you should have the following branches:
1. the default branch that holds latest dev work for `iroha2`. Name it `main` or `dev` if you want to
2. a branch that holds latest stable release of `iroha2`. I would call it `stable`
3. a branch that holds latest lts release of `iroha2`. I would call it `lts`
4. branch `iroha1-main`
5. branch `iroha1-stable`
6. branch `iroha1-lts`

Except for 1. and 4. I consider all other branches optional. I would say that whoever wants to build a release of iroha should checkout the corresponding tag and build it from there
