### ISSUE TITLE
[BUG] duplicate query

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha-java#432]
Environment:

1. Iroha commit: `version="2.0.0-pre-rc.22.0" git_commit_sha="a62640d8a"`
2. java-sdk commit: e23b548
3. deployment to longevity stand: linux х64 + k8s

step to reproduce:

1. sendQuery findAllAsset or findAllAccount
2. check log on opensearch

Expected result:
query not duplicate

Actual result:
query was duplicated

not sure if it's related to queries findAllAsset or findAllAccount

[duplicate_queries.log](https://github.com/user-attachments/files/16542162/duplicate_queries.log)

**Comment by Mingela** [comment]
@timofeevmd could you elaborate on the issue please?
I can see the logs are composed of pairs:
```
tower_http::trace::on_request: started processing request
..
tower_http::trace::on_response: finished processing request latency=0 ms status=200
```
I could not find any duplications

**Comment by mversic** [comment]
who is making log entries? is it iroha? I was wondering why do we see 2 log entries for every query?

**Comment by Mingela** [comment]
> who is making log entries? is it iroha? I was wondering why do we see 2 log entries for every query?

there are log entries for respective request and response for the same query, there are no duplications, please check the file carefully

most likely the logs emitted by an infrastructure proxy/sidecar

**Comment by timofeevmd** [comment]
Indeed, thanks for the comment, the ticket can be closed...
