### ISSUE TITLE
Maven entry is outdated (0.0.8)

### ISSUE THREAD

**Issue by Ambrevar** [hyperledger/iroha-java#54]
See https://search.maven.org/artifact/jp.co.soramitsu/iroha.
Would it be possible to update it?
It could be useful in particular for those who cannot set up a full JDK environment to build iroha-java.
Thanks!

**Comment by Warchant** [comment]
Use jitpack https://jitpack.io/#hyperledger/iroha-java/6.1.0

**Comment by Ambrevar** [comment]
Thanks, didn't know about Jitpack, good tip!

Question: Why is Jitpack referring to tag 6.1.0 while the latest release
is 1.1.0 on GitHub?

I've added the Jitpack lines to my Leiningen project, then running `lein
deps` I get

```
> lein deps
Retrieving com/github/hyperledger/iroha-java/client/6.1.0/client-6.1.0.pom from jitpack
...
Retrieving com/github/hyperledger/iroha-java/client/6.1.0/client-6.1.0.jar from jitpack
Could not find artifact io.grpc:protoc-gen-grpc-java:jar:1.12.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact io.grpc:protoc-gen-grpc-java:jar:1.12.0 in clojars (https://repo.clojars.org/)
Could not find artifact io.grpc:protoc-gen-grpc-java:jar:1.12.0 in jitpack (https://jitpack.io)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

Any clue why io.grpc:protoc-gen-grpc-java cannot be fetched?  (I'm not
behind a proxy.)

**Comment by Warchant** [comment]
@Ambrevar pay attention that actual tag name is different from version in a title.
![image](https://user-images.githubusercontent.com/1867551/77636091-3f6cf100-6f5c-11ea-9333-33a26308f86e.png)

Tag name is a semver version of iroha-java library itself. Title version describes compatibility with Iroha.

**Comment by Ambrevar** [comment]
Oh, indeed, makes sense now, thanks!
