### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [hyperledger/iroha-java#55]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Warchant** [comment]
This library should work for Android apps. Will we be able to use it with bouncycastle?

AFAIK spongycastle is just a rename of bouncycastle, with a couple fixes to work on Android:
https://en.wikipedia.org/wiki/Bouncy_Castle_(cryptography)#Spongy_Castle

**Comment by Neustradamus** [comment]
@Warchant: Thanks for your comment!
Currently Bouncy Castle last version is 1.65 and Spongy Castle last version is 1.58.
Spongy Castle is a fork of Bouncy Castle.
Please look previous links :)

Since several years, a lot of projects have already moved from Spongy Castle to Bouncy Castle because the project is dead.

You can see discussion "34" in https://github.com/rtyley/spongycastle/issues.

**Comment by Neustradamus** [comment]
@Warchant: New CVEs, there is now 1.68.

**Comment by ryjones** [comment]
@hyperledger/iroha-maintainers

**Comment by Neustradamus** [comment]
Currently the latest version is 1.69.

**Comment by Mingela** [comment]
@Neustradamus feel free to check and close the issue

**Comment by Neustradamus** [comment]
@Mingela: I do not understand, what is the version of Bouncy Castle ?

**Comment by ryjones** [comment]
@Neustradamus from [here](https://github.com/soramitsu/iroha-ed25519-sha3-java/pull/1/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R24), it looks like `1.69` ([line 24](https://github.com/soramitsu/iroha-ed25519-sha3-java/blob/20a42e3f0223d899e0c11a8faac7c447f3bccf79/build.gradle#L24))

**Comment by Neustradamus** [comment]
@Mingela: Thanks for your change! :)
@ryjones: Thanks for this detail! :)

**Comment by kamilsa** [comment]
issue resolved, feel free to reopen if something was done wrong
