### ISSUE TITLE
use .jar in xamarin 

### ISSUE THREAD

**Issue by SalimiHabib** [hyperledger/iroha-java#66]
Is it possible to use this client with binding library on xamarin android project ?

**Comment by LiraLemur** [comment]
@SalimiHabib Hi! Please clarify your question in one of our chats: https://github.com/hyperledger/iroha#need-help

I'll try to find an Android developer to help you there :)

**Comment by SalimiHabib** [comment]
xamarin have ability to interop with java and c++ by some type of library that they named binding library
it is a separate assembly that created by adding java .jar file to it and it create binding with exposed objects of that jar file automatically .
because calling gRPC over HTTP/2 with Grpc.Net.Client is currently not supported on Xamarin  , i think may be it is possible to try it  in this way to connect from xamarin to torri service .
But I could not do that  and my shared project cannot recognize banded library 
after all these effort i change my plane and use grpc client in server side from asp .net core web site and its work fine 

thank you
