### ISSUE TITLE
Travis CI is no longer supported

### ISSUE THREAD

**Issue by ryjones** [hyperledger/iroha-java#69]
Travis CI has changed how open source projects are supported, and Hyperledger can no longer build there. I suggest Azure Pipelines or GitHub Actions as a replacement.

**Comment by vadimreutskiy** [comment]
Thanks, Ry!

We will soon mitigate that issue.

**Comment by ryjones** [comment]
@hyperledger/iroha-maintainers

**Comment by BulatSaif** [comment]
Resolved in https://github.com/hyperledger/iroha-java/pull/71 and https://github.com/hyperledger/iroha-java/pull/72
